%% This file is autogenerated ...

%% This file contains virtual vehicle configuration information.

%% This file is saved at time 06-Feb-2026 15:01:31
                     ConfigInfos.Version = '25.2.0.3123386 (R2025b) Update 3';
                   ConfigInfos.SessionID = 'ConfiguredVirtualPRIUS.m';
                   ConfigInfos.LicStatus = [1,1,1,1,1,1,1,1,1];
                ConfigInfos.ProjPathText = '/MATLAB Drive/Examples/R2025b/projects';
                    ConfigInfos.ProjPath = '/MATLAB Drive/Examples/R2025b/projects/VirtualVehicle4/VirtualVehicle';
                 ConfigInfos.SessionName = 'ConfiguredVirtualPRIUS';
                 ConfigInfos.XmlPathText = '/MATLAB Drive/Examples/R2025b/projects/VVCCustomCatalog.xml';
               ConfigInfos.TemplateModel = 'VirtualVehicleTemplateArchitecture';
          ConfigInfos.TemplatePlantModel = 'SimulinkPlantModelsArchitecture';
                 ConfigInfos.ConfigModel = 'ConfiguredVirtualVehicleModel';
            ConfigInfos.ConfigPlantModel = 'ConfiguredSimulinkPlantModel';
                    ConfigInfos.VehClass = 'Passenger Vehicle';
                     ConfigInfos.VehArct = 'Hybrid Electric Vehicle IPS';
                      ConfigInfos.VehDyn = 0;
              ConfigInfos.PlantModelType = 'Simulink';
                  ConfigInfos.VehChassis = 'Vehicle Body 3DOF Longitudinal';
%% Vehicle Configuration
ConfigInfos.FeatureVariantSelectedMap=containers.Map;
ConfigInfos.FeatureVariantSelectedMap('Active Differential Control') = 'No Control';
ConfigInfos.FeatureVariantSelectedMap('Axle Interconnect') = 'No Interconnect';
ConfigInfos.FeatureVariantSelectedMap('Battery Management System') = 'No BMS';
ConfigInfos.FeatureVariantSelectedMap('Body and Frame') = 'Vehicle Body 3DOF Longitudinal';
ConfigInfos.FeatureVariantSelectedMap('Brake Control Unit') = 'Open Loop';
ConfigInfos.FeatureVariantSelectedMap('Brake System') = 'Brake System';
ConfigInfos.FeatureVariantSelectedMap('DC-DC Converter') = 'HVDCPassThrough';
ConfigInfos.FeatureVariantSelectedMap('Drive Shaft Torque Routing') = 'One Actuator FWD';
ConfigInfos.FeatureVariantSelectedMap('Driver') = 'Longitudinal Driver';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain') = 'Front Wheel Drive';
ConfigInfos.FeatureVariantSelectedMap('Drivetrain Wheel Speed Route') = 'Bus';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 1') = 'Hybrid Electric Vehicle IPS - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 2') = 'Hybrid Electric Vehicle IPS - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 3') = 'Electric Vehicle 3EM Dual Front - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Machine 4') = 'Electric Vehicle 4EM - Mapped Motor';
ConfigInfos.FeatureVariantSelectedMap('Electric Motors') = '2EM';
ConfigInfos.FeatureVariantSelectedMap('Energy Storage') = 'Mapped Battery (Hybrid Electric Vehicle IPS)';
ConfigInfos.FeatureVariantSelectedMap('Engine') = 'SI Mapped Engine';
ConfigInfos.FeatureVariantSelectedMap('Engine Control Unit') = 'SI Engine Controller';
ConfigInfos.FeatureVariantSelectedMap('Environment') = 'Ambient Conditions';
ConfigInfos.FeatureVariantSelectedMap('Final Drive') = 'Final Drive';
ConfigInfos.FeatureVariantSelectedMap('Front Axle Compliances') = 'Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Front Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Front Differential System') = 'Open Differential';
ConfigInfos.FeatureVariantSelectedMap('Front Suspension') = 'No Suspension Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire Data') = 'MF Tires Longitudinal Front';
ConfigInfos.FeatureVariantSelectedMap('Front Tire and Wheel') = 'MF Tires Longitudinal Front';
ConfigInfos.FeatureVariantSelectedMap('Hitch') = 'Hitch 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Power Generation') = 'Power Generation';
ConfigInfos.FeatureVariantSelectedMap('Powertrain') = 'Hybrid Electric Vehicle IPS';
ConfigInfos.FeatureVariantSelectedMap('Rear Axle Compliances') = 'No Axle Compliances';
ConfigInfos.FeatureVariantSelectedMap('Rear Brake Type') = 'Disc';
ConfigInfos.FeatureVariantSelectedMap('Rear Differential System') = 'No Differential Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Suspension') = 'No Suspension Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire Data') = 'MF Tires Longitudinal Rear';
ConfigInfos.FeatureVariantSelectedMap('Rear Tire and Wheel') = 'MF Tires Longitudinal Rear';
ConfigInfos.FeatureVariantSelectedMap('Refrigeration Loop') = 'System Level';
ConfigInfos.FeatureVariantSelectedMap('Sensor') = 'No IMU Sensor';
ConfigInfos.FeatureVariantSelectedMap('Steering System') = 'No Steering';
ConfigInfos.FeatureVariantSelectedMap('Suspension System') = 'Suspension System';
ConfigInfos.FeatureVariantSelectedMap('Thermal Control Unit') = 'No Thermal Control';
ConfigInfos.FeatureVariantSelectedMap('Thermal System') = 'Constant Temperature';
ConfigInfos.FeatureVariantSelectedMap('Tire and Wheel System') = 'Tire and Wheel System';
ConfigInfos.FeatureVariantSelectedMap('Trailer') = 'No Trailer';
ConfigInfos.FeatureVariantSelectedMap('Trailer Body') = 'Trailer Body 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Suspension') = 'Z Force Splice 3DOF';
ConfigInfos.FeatureVariantSelectedMap('Trailer Tire') = 'MF Tires Longitudinal and Lateral';
ConfigInfos.FeatureVariantSelectedMap('Transmission') = 'Ideal Fixed Gear Transmission';
ConfigInfos.FeatureVariantSelectedMap('Transmission Control Unit') = 'Driver Pass Through';
ConfigInfos.FeatureVariantSelectedMap('Variant Source') = 'One Actuator FWD';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Architecture') = 'Hybrid Electric Vehicle IPS';
ConfigInfos.FeatureVariantSelectedMap('Vehicle Control Unit') = 'HEVIPS RuleBased';

%% User Modified Data

           ConfigInfos.DataModified{1,1} = 'PlntVehMass';
           ConfigInfos.DataModified{1,2} = '1370';
           ConfigInfos.DataModified{1,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{1,4} = 'PlntVehMass';
           ConfigInfos.DataModified{1,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{1,6} = 'Body and Frame';

           ConfigInfos.DataModified{2,1} = 'PlntVehDstCGFrntAxl';
           ConfigInfos.DataModified{2,2} = '1.20';
           ConfigInfos.DataModified{2,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{2,4} = 'PlntVehDstCGFrntAxl';
           ConfigInfos.DataModified{2,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{2,6} = 'Body and Frame';

           ConfigInfos.DataModified{3,1} = 'PlntVehDstCGRearAxl';
           ConfigInfos.DataModified{3,2} = '1.55';
           ConfigInfos.DataModified{3,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{3,4} = 'PlntVehDstCGRearAxl';
           ConfigInfos.DataModified{3,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{3,6} = 'Body and Frame';

           ConfigInfos.DataModified{4,1} = 'PlntVehCGHgtAxl';
           ConfigInfos.DataModified{4,2} = '0.55';
           ConfigInfos.DataModified{4,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{4,4} = 'PlntVehCGHgtAxl';
           ConfigInfos.DataModified{4,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{4,6} = 'Body and Frame';

           ConfigInfos.DataModified{5,1} = 'PlntVehAeroFrntArea';
           ConfigInfos.DataModified{5,2} = '2.2';
           ConfigInfos.DataModified{5,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{5,4} = 'PlntVehAeroFrntArea';
           ConfigInfos.DataModified{5,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{5,6} = 'Body and Frame';

           ConfigInfos.DataModified{6,1} = 'PlntVehAeroDragCff';
           ConfigInfos.DataModified{6,2} = '0.24';
           ConfigInfos.DataModified{6,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{6,4} = 'PlntVehAeroDragCff';
           ConfigInfos.DataModified{6,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{6,6} = 'Body and Frame';

           ConfigInfos.DataModified{7,1} = 'PlntVehAeroLiftCff';
           ConfigInfos.DataModified{7,2} = '0';
           ConfigInfos.DataModified{7,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{7,4} = 'PlntVehAeroLiftCff';
           ConfigInfos.DataModified{7,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{7,6} = 'Body and Frame';

           ConfigInfos.DataModified{8,1} = 'PlntVehAeroPitchCff';
           ConfigInfos.DataModified{8,2} = '0';
           ConfigInfos.DataModified{8,3} = 'PassVeh.sldd';
           ConfigInfos.DataModified{8,4} = 'PlntVehAeroPitchCff';
           ConfigInfos.DataModified{8,5} = 'Vehicle Body 3DOF Longitudinal';
           ConfigInfos.DataModified{8,6} = 'Body and Frame';

%% Test Plan
          ConfigInfos.TestPlan{1}.Source = 'Scenario.sldd';
            ConfigInfos.TestPlan{1}.Name = 'Drive Cycle';
           ConfigInfos.TestPlan{1}.Cycle = 'FTP75';
          ConfigInfos.TestPlan{1}.Driver = 'Longitudinal Driver';
       ConfigInfos.TestPlan{1}.Data{1,1} = 'ScnSimTime';
       ConfigInfos.TestPlan{1}.Data{1,2} = '2474';
       ConfigInfos.TestPlan{1}.Data{2,1} = 'ScnLongVelUnit';
       ConfigInfos.TestPlan{1}.Data{2,2} = 'mph';
       ConfigInfos.TestPlan{1}.Data{3,1} = 'PlntVehInitVertPos';
       ConfigInfos.TestPlan{1}.Data{3,2} = '0';
       ConfigInfos.TestPlan{1}.Data{4,1} = 'DriverPreviewDist';
       ConfigInfos.TestPlan{1}.Data{4,2} = '4';
       ConfigInfos.TestPlan{1}.Data{5,1} = 'DriverTimeConst';
       ConfigInfos.TestPlan{1}.Data{5,2} = '0.3';
       ConfigInfos.TestPlan{1}.Data{6,1} = 'PlntVehInitLatPos';
       ConfigInfos.TestPlan{1}.Data{6,2} = '0';
       ConfigInfos.TestPlan{1}.Data{7,1} = 'DriverAeroRes';
       ConfigInfos.TestPlan{1}.Data{7,2} = '0.5';
       ConfigInfos.TestPlan{1}.Data{8,1} = 'DriverDrivelineRes';
       ConfigInfos.TestPlan{1}.Data{8,2} = '75';
       ConfigInfos.TestPlan{1}.Data{9,1} = 'DriverRollRes';
       ConfigInfos.TestPlan{1}.Data{9,2} = '200';
      ConfigInfos.TestPlan{1}.Data{10,1} = 'DriverTractiveForce';
      ConfigInfos.TestPlan{1}.Data{10,2} = '15000';

%% Selected Logging Signals
ConfigInfos.SelectedSignals = {
'Battery.BattInfo.BattCurr',...
'Battery.BattInfo.BattPwr',...
'Battery.BattInfo.BattSoc',...
'Battery.BattInfo.BattVolt',...
'EM.EMPwrElec',...
'EM.EMSpd',...
'EM.EMTrq',...
'Engine.EngSpdOut',...
'Engine.EngTrq',...
'Engine.EngTrqCrk',...
'Engine.FuelFlw',...
};

%% Finish
